In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


## Introduction to Tensors

### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get scalet back as python int
scalar.item()

7

In [5]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
#number of dimensions
vector.ndim

1

In [7]:
#shape
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [9]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [10]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors

why random tensors?
Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

' Start with random numbers -> look at data -> update random numbers -> look at data -> Update random numbers '

In [11]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5598, 0.4756, 0.7284, 0.1534],
        [0.4560, 0.0499, 0.2775, 0.7960],
        [0.0307, 0.2763, 0.0086, 0.5651]])

In [12]:
random_tensor.ndim

2

In [13]:
# create a random tensor similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #(height,width,colour_channels[R,G,B]) 
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and Ones

In [16]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [19]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data types
**Note:** Tensor datatypes is one of the three big errors you will run into with pytorch and deep learning :
1. Tensor not right datatype
2. Tensor not the right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [22]:
# float32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what data type is the tensor (e.g. float32 or float16)
                               device = None, # What device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], 
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from a tensor: (tensor attributes)
1. Tensor not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensor not the right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [28]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3823, 0.6781, 0.9588, 0.3356],
        [0.8317, 0.3533, 0.9010, 0.3904],
        [0.0167, 0.3716, 0.1809, 0.2741]])

In [29]:
#find out deatils about some tensor
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.3823, 0.6781, 0.9588, 0.3356],
        [0.8317, 0.3533, 0.9010, 0.3904],
        [0.0167, 0.3716, 0.1809, 0.2741]])
torch.float32
torch.Size([3, 4])
cpu


### Manipulating tensors (Tensor operations):

Tensor operations include:
* addition
* subtraction
* multiplication (element-wise)
* division
* Matrix multiplication

In [30]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# multiply the tensor by 10
tensor * 10

tensor([10, 20, 30])

In [32]:
# subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [33]:
# try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [34]:
#addition 
torch.add(tensor, 10)

tensor([11, 12, 13])