In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


## Introduction to Tensors

### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get scalet back as python int
scalar.item()

7

In [5]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
#number of dimensions
vector.ndim

1

In [7]:
#shape
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [9]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [10]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors

why random tensors?
Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

' Start with random numbers -> look at data -> update random numbers -> look at data -> Update random numbers '

In [11]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1967, 0.1172, 0.2428, 0.0610],
        [0.3621, 0.6043, 0.9425, 0.1999],
        [0.5732, 0.0736, 0.3338, 0.3621]])

In [12]:
random_tensor.ndim

2

In [13]:
# create a random tensor similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #(height,width,colour_channels[R,G,B]) 
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and Ones

In [14]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [17]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor data types
**Note:** Tensor datatypes is one of the three big errors you will run into with pytorch and deep learning :
1. Tensor not right datatype
2. Tensor not the right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [20]:
# float32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what data type is the tensor (e.g. float32 or float16)
                               device = None, # What device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [21]:
float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [24]:
int_32_tensor = torch.tensor([3, 6, 9], 
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [25]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from a tensor: (tensor attributes)
1. Tensor not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensor not the right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [26]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2614, 0.0330, 0.0379, 0.5969],
        [0.8824, 0.8396, 0.2234, 0.0936],
        [0.2200, 0.4790, 0.6118, 0.8696]])

In [27]:
#find out deatils about some tensor
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.2614, 0.0330, 0.0379, 0.5969],
        [0.8824, 0.8396, 0.2234, 0.0936],
        [0.2200, 0.4790, 0.6118, 0.8696]])
torch.float32
torch.Size([3, 4])
cpu


### Manipulating tensors (Tensor operations):

Tensor operations include:
* addition
* subtraction
* multiplication (element-wise)
* division
* Matrix multiplication

In [28]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [29]:
# multiply the tensor by 10
tensor * 10

tensor([10, 20, 30])

In [30]:
# subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [31]:
# try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
#addition 
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication:

Two main ways of performing multiplication in neural networks and deep learning
1. Element wise multiplication
2. Matrix Multiplication

There are two rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**:
* '(2,3)@(3,2) -> (2,2)'
* '(3,2)@(2,3) -> (3,3)'

In [33]:
# element wise multiplication
print(tensor)
print(tensor * tensor)

tensor([1, 2, 3])
tensor([1, 4, 9])


In [34]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
%%time
value=0
for i in range(len(tensor)):
    value+= tensor[i]*tensor[i]
value

CPU times: total: 0 ns
Wall time: 2.99 ms


tensor(14)

In [36]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning : Shape error

In [37]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B= torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A,tensor_B) #toech.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [38]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**:

a **transpose** switches the axes or dimensions of a given tensor.

In [39]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [40]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [41]:
#the matrix multiplication operation works when tensor_B is transposed
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [42]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

## Finding the min, max, mean, sum, etc (tensor aggregation):


In [43]:
#create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [44]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [45]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [46]:
# find the mean : Note: the torch.mean() function tequires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
#find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

### Finding the positional min and max

In [48]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# finding the index of the min element
x.argmin()

tensor(0)

In [50]:
# finding the index of the max element
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, unsqueezing

* reshaping - reshapes an input tensor to a defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory as the orignal tensor
* stacking - combining multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all '1' dimensions from a tensor 
* unsqueeze - adds a '1' dimension to a target tensor 
* permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [51]:
# create a tensor
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# changing z changes x (because view of a tensor shares the same memory as the orignal input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [55]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
#torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

#remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New tensoe shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensoe shape: torch.Size([9])


In [57]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f'previous target: {x_squeezed}')
print(f'previous shape: {x_squeezed.shape} \n')

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'new target: {x_unsqueezed}')
print(f'new shape: {x_unsqueezed.shape}')

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9]) 

new target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [58]:
# torch.permute - rearranges the dimeanions of a tensor in a specefied order 
x_original = torch.rand(size=(224,224,3)) #height, width, colourchannels

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis

print(f'Previous Shape : {x_original.shape}')
print(f'New shape : {x_permuted.shape}')

Previous Shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [59]:
x_original[0,0,0]=0.1
x_permuted[0,0,0]

tensor(0.1000)

### Indexing (selecting data from tensors)
Indexing in pytorch is similar to indexing in numpy

In [60]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
#Lets index o our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
#Lets index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [63]:
#Lets index on the inner most bracket
x[0,2,2]

tensor(9)

In [64]:
#You can use ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [65]:
# Get all the values of 0th and 1st dimensions but only index 1 of 2nd dimeanion
x[:,:,1]

tensor([[2, 5, 8]])

In [66]:
# Get all the values of the 0 dimension but only the 1 index value of 1st and 2nd dimenison
x[:,1,1]

tensor([5])

In [67]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimenison
x[0,0,:]

tensor([1, 2, 3])

In [71]:
# Index on x to return 9
print(x[0,0,2])
# Index on x to return 3,6,9
print(x[:,:,2])

tensor(3)


tensor([[3, 6, 9]])

##  Pytorch tensors and numpy

NumPy is a popular scientific Python computing library

And beacuse of this, Python has functionality to interact with it

* Data in numpy, Want it in pytorch tensor -> torch.tfrom_numpy(ndarray)
* Pytorch tensor to Numpy -> torch.tensor.numpy()

In [72]:
#Numpy array to tensor
import numpy as np
array = np.arange(1.0,8.0)
tensor  = torch.from_numpy(array)
# when converting from numpy -> Pytorch, Pytorch reflects numpy's default data type of float64 unless specefied otherwise

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
# Change the value of array, what will it do to the tensor?
array=array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
numpy_tensor.dtype

dtype('float32')

In [76]:
# Change the tensor, What happens to the numpy tensor?
tensor = tensor + 1
tensor, numpy_tensor 

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take the random out of random) 

In short how a neural network learns:
start with random numbers -> tensor operations -> update from random numbers to try and make them better representations
of the data -> again -> again -> again.. 

To reduce the randomness in a neural networks and Pytorch comes the concept of **Random seed**
Essentially what the random seed does is "flavor" the randomness.

In [79]:
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6417, 0.1283, 0.9307, 0.6011],
        [0.7243, 0.6550, 0.4873, 0.9377],
        [0.4097, 0.8921, 0.2207, 0.9583]])
tensor([[0.2513, 0.3988, 0.5215, 0.8929],
        [0.5338, 0.0060, 0.2096, 0.7683],
        [0.5897, 0.0418, 0.0716, 0.4998]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [81]:
# Lets make some random but reproducable tensors

#set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducability:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed


## Running tensors and Pytorch objects on the GPU's (and making faster computations)
